import type { ClashCard } from "../models/ClashCard-Model";

const ClashCards: ClashCard[] = [
  { "nome": "Mago", "emojis": ["🧙‍♂️", "🔥", "✨"], "foto": "https://4.bp.blogspot.com/-ayolU8UXcNo/WQExTxbkeKI/AAAAAAAAzgE/nRtnu-QFN9ESjWRzhwMj40GwTfcwvm2cACLcB/s1600/mago-clash-royale.png" },
  { "nome": "Gigante", "emojis": ["👹", "👊", "🏰"], "foto": "https://2.bp.blogspot.com/-w01kph8d4jI/WQExSYUrHVI/AAAAAAAAzfM/PH0XRHnrQSUti100RL9fZwhJF7grWk-AACLcB/s1600/gigante-clash-royale-card.png" },
  { "nome": "Arqueiras", "emojis": ["🏹", "👧", "👧"], "foto": "https://2.bp.blogspot.com/-N9yfj4eLVgk/WQExOrDl2II/AAAAAAAAzdI/sX8P1ZCeVdoAEZfh5ejxvoc78N4u5FXnwCLcB/s1600/arqueiras-clash-royale.png" },
  { "nome": "Golem", "emojis": ["🪨", "💥", "🦾"], "foto": "https://1.bp.blogspot.com/-GQoFjMs6BQQ/WQExS55AdtI/AAAAAAAAzfg/Q4vEgCX44ZwKWTOzKs6mjQ_asdPX9VnDQCLcB/s1600/golem-clash-royale.png" },
  { "nome": "Príncipe", "emojis": ["🤴", "🐎", "⚡"], "foto": "https://4.bp.blogspot.com/-dOvCRIzkRXw/WQExU2gCWuI/AAAAAAAAzgk/7PUuvhaLm8Mkn3iSbjlnmQIb-LaM_7HRQCLcB/s1600/principe-clash-royale-carta-epica.png" },
  { "nome": "Destruidores de Muros", "emojis": ["💀", "💣", "💥"], "foto": "https://www.clashroyaledicas.com/wp-content/uploads/2019/01/carta-destruidores-de-muros-clash-royale.png" },
  { "nome": "Domadora de Carneiro ", "emojis": ["🐐", "👧🏾", "💨"], "foto": "https://www.clashroyaledicas.com/wp-content/uploads/2019/06/carta-domadora-de-carneiro-clash-royale.png" },
  { "nome": "Princesa", "emojis": ["👸", "🏹", "🎯"], "foto": "https://www.clashroyaledicas.com/wp-content/uploads/2016/03/princesa-wiki-da-carta.png" },
  { "nome": "Príncipe das trevas", "emojis": ["🤴", "🐎", "🛡️"], "foto": "https://4.bp.blogspot.com/-c0LYIchlIak/WQExUxLf9oI/AAAAAAAAzgo/Za64luiIR-475HgK0h2zuP2JI98L0o9bgCLcB/s1600/principe-das-trevas-clash-royale.png" },
  { "nome": "Três Mosqueteiras", "emojis": ["👩", "🔫", "3️⃣"], "foto": "https://www.clashroyaledicas.com/wp-content/uploads/2019/05/tres-mosqueteiras-clash-royale.png" },
  { "nome": "Bebê Dragão", "emojis": ["🐲", "👶", "🔥"], "foto": "https://3.bp.blogspot.com/-7He-SnfbSG4/WQExQj-nSfI/AAAAAAAAzeQ/2OTLSNu1RrUvX4H9ECrP3x_0MOBlUGNOQCLcB/s1600/dragao-bebe-baby_dragon-clash-royale.png" },
  { "nome": "P.E.K.K.A", "emojis": ["🤖", "⚔️", "💜"], "foto": "https://4.bp.blogspot.com/-CO9J5mVvDTo/WQExRvcFrhI/AAAAAAAAze0/vJN16iN0doABNK-VqRYV1YRK72o5aoUXgCLcB/s1600/feitico-de-gelo-clash-royale-card.png" },
  { "nome": "Mosqueteira", "emojis": ["👩‍🎤", "🔫", "🎯"], "foto": "https://2.bp.blogspot.com/-eMmF2Z16ex8/WQExUmBFdnI/AAAAAAAAzgc/i-YwpbTxeyAG8hu4UslrNx-vWiWMM4-rgCLcB/s1600/mosqueteira-clash-royale-rara-carta.png" },
  { "nome": "Horda de Servos", "emojis": ["👾", "👾", "👾"], "foto": "https://3.bp.blogspot.com/-BxH1AyHPRzU/WQExTQBx6wI/AAAAAAAAzfs/MaL9PzN7QGgWA3wPkg-TJ8BYGrwilFdvwCLcB/s1600/horda-de-servos-clash-royale.png" },
  { "nome": "Bola de Fogo", "emojis": ["🔥", "⚽", "💥"], "foto": "https://1.bp.blogspot.com/-_iIakxErh7w/WQExPaHnJEI/AAAAAAAAzdc/rjhr_C3mpcwLu7sW48djgY-jL0s6odzhACLcB/s1600/bola-de-fogo-clash-royale-fireball.png" },
  { "nome": "Mini P.E.K.K.A", "emojis": ["🤖", "🥞", "⚔️"], "foto": "https://3.bp.blogspot.com/-WLXOlz-lZlg/WQExUQ7i8mI/AAAAAAAAzgQ/0dm41b88iI0aUaFJzJHnDVWo5aGevd0bACLcB/s1600/mini_PEKKA-clash-royale.png" },
  { "nome": "Valquíria", "emojis": ["👩‍🦰", "🪓", "🔄"], "foto": "https://www.clashroyaledicas.com/wp-content/uploads/2022/04/valquiria-clash-royale.png" },
  { "nome": "Goblins", "emojis": ["👺", "🗡️", "💚"], "foto": "https://2.bp.blogspot.com/-Z2EFMj4A8sU/WQExSntFQnI/AAAAAAAAzfY/iBAYBQQFGskETiDIGYlYkgwmxafMNwMrACLcB/s1600/goblins-clash-royale-card.png" },
  { "nome": "Corredor", "emojis": ["🐗", "🏃", "💨"], "foto": "https://1.bp.blogspot.com/-p1C7Y1AqSDU/WQExQgkWZFI/AAAAAAAAzeM/XRnBKhAfMncYL7FwRz1W2gULyMiq3tOAQCLcB/s1600/corredor-clash-royale-carta-rara.png" },
  { "nome": "Bruxa Sombria", "emojis": ["🧙‍♀️", "🦇", "🌑"], "foto": "https://1.bp.blogspot.com/-P3N8svhi-CE/WQE4KrtRF3I/AAAAAAAAzh0/oJQ3f4khDoMl3o2YImahOc4RKdDkTbV7wCLcB/s1600/bruxa-sombria-clash-royale-wiki.png" },
  { "nome": "Bruxa", "emojis": ["🧙‍♀️", "💀", "🐷"], "foto": "https://4.bp.blogspot.com/-jYcsFOil1Kw/WQExPVoEN4I/AAAAAAAAzdk/fwG-X_LiGykSV9Gr3Vn_LbkYfnn08dTswCLcB/s1600/bruxa-clash-royale.png" },
  { "nome": "Mago de Gelo", "emojis": ["🧙‍♂️", "❄️", "💧"], "foto": "https://www.clashroyaledicas.com/wp-content/uploads/2016/03/mago-de-gelo-wiki-da-carta.png" },
  { "nome": "Mega Servo", "emojis": ["👾", "🦾", "🛡️"], "foto": "https://3.bp.blogspot.com/-4af3VwBDZFI/WQExUBuBxoI/AAAAAAAAzgM/9l-Mvg8ciKgV1moeRL25ZZOjkPS6IRZKQCLcB/s1600/megasservo.png"},
  { "nome": "X-Besta", "emojis": ["🏹", "❌", "🛡️"], "foto": "https://3.bp.blogspot.com/-YF0NgDIbAj8/WQExWfS11LI/AAAAAAAAzhY/WFCKzwEVCCsbgf977nkznKNzbiCBnJrQwCLcB/s1600/x-besta-clash-royale.png"},
  { "nome": "Executor", "emojis": ["🪓", "👨‍🦲", "🌊"], "foto": "https://www.clashroyaledicas.com/wp-content/uploads/2016/12/carta-executor-clash-royale.png" },
  { "nome": "Lançador", "emojis": ["😈", "🪨", "🎳"], "foto": "https://4.bp.blogspot.com/-aFiGhIS5gIc/WQExTWCzPwI/AAAAAAAAzfw/AqwLRgmxcicH1JxmKP1UOsICHOOqltLBwCLcB/s1600/lancador-clash-royale.png" },
  { "nome": "Dragão Infernal", "emojis": ["🐲", "🔥", "🔗"], "foto": "https://1.bp.blogspot.com/-ZdGVasncA_U/WQExQ-GIzoI/AAAAAAAAzeY/9jM_GQv1tgkSWNfqI2lBj7cczUT5IASPwCLcB/s1600/dragao-infernal-clash-royale.png" },
  { "nome": "Cavaleiro", "emojis": ["🤺", "🛡️", "🐴"], "foto": "https://2.bp.blogspot.com/-giVBXji3lmk/WQExQMFbAEI/AAAAAAAAzd8/4I2McpmluN0a4jQ7_4ZG2gyb4-etqK5BgCLcB/s1600/cavaleiro-clash-royale-carta.png" },
  { "nome": "Esqueleto", "emojis": ["💀", "🦴", "⚔️"], "foto": "https://2.bp.blogspot.com/-Dsxy-cphfBM/WQExRc7iTmI/AAAAAAAAzeo/EID-vfe0CuErv2oZVln1qWctqIwRPGvjwCLcB/s1600/esqueletos-clash-royale.png" },
  { "nome": "Exército de Esqueletos", "emojis": ["💀", "💀", "💀"], "foto": "https://1.bp.blogspot.com/-_eWPeNr1Xec/WQExRnw1NDI/AAAAAAAAzew/2DUgEhZvJ5seNyUrF_BfsuUbwY9E5KLoQCLcB/s1600/exercito-de-esqueletos-clash-royale.png" },
  { "nome": "Bombardeiro", "emojis": ["💣", "👦", "💥"], "foto": "https://www.clashroyaledicas.com/wp-content/uploads/2016/02/bombardeiro-wiki-da-carta.png" },
  { "nome": "Canhão", "emojis": ["🔫", "🏰", "⚙️"], "foto": "https://3.bp.blogspot.com/-db91vRcHAUw/WQExP3uwP9I/AAAAAAAAzd0/-PTG_1uJXfg6U2cnSS0dMUWRmcDJlD_YwCLcB/s1600/card-canhao-clash-royale-cannon.png" },
  { "nome": "Tesla", "emojis": ["⚡", "🗼", "🔩"], "foto": "https://www.clashroyaledicas.com/wp-content/uploads/2019/07/carta-tesla-clash-royale.png" },
  { "nome": "Torre Inferno", "emojis": ["🗼", "🔥", "🔗"], "foto": "https://3.bp.blogspot.com/-2S9sDqbOrRM/WQExV4hnlII/AAAAAAAAzhE/SlSUNPpqnhsWdczi_rESYJCUtNTetLV7gCLcB/s1600/torre-inferno-clash-royale.png" },
  { "nome": "Torre de Bombas", "emojis": ["🗼", "💣", "💥"], "foto": "https://www.clashroyaledicas.com/wp-content/uploads/2016/02/torre-de-bombas-clash-royale.png" },
  { "nome": "Cabana de Bárbaros", "emojis": ["🏚️", "⚔️", "👨"], "foto": "https://www.clashroyaledicas.com/wp-content/uploads/2016/02/cabana-de-barbaros-wiki-da-carta.png" },
  { "nome": "Cabana de Goblins", "emojis": ["🏚️", "👺", "🗡️"], "foto": "https://www.clashroyaledicas.com/wp-content/uploads/2019/07/carta-cabana-de-goblins-clash-royale.png" },
  { "nome": "Fornalha", "emojis": ["🏭", "🔥", "🛢️"], "foto": "https://www.clashroyaledicas.com/wp-content/uploads/2016/05/carta-fornalha-clash-royale-zsIYES.png" },
  { "nome": "Choque", "emojis": ["⚡", "💥", "🔋"], "foto": "https://www.clashroyaledicas.com/wp-content/uploads/2016/05/carta-choque-clash-royale.png" },
  { "nome": "Flechas", "emojis": ["🏹", "➡️", "🎯"], "foto":"https://3.bp.blogspot.com/-9Y83SQcG5tI/WQExR3FXimI/AAAAAAAAze4/D11dY8R6-3Af44GThzBOFtNxMBC967uYgCLcB/s1600/flechas-arrows-clash-royale.png" },
  { "nome": "Bola de Neve", "emojis": ["❄️", "⚪", "💥"], "foto": "https://www.clashroyaledicas.com/wp-content/uploads/2018/06/carta-bola-de-neve-no-clash-royale.png" },
  { "nome": "Veneno", "emojis": ["☠️", "🧪", "💚"], "foto": "https://4.bp.blogspot.com/-prQZpwF8I74/WQExWbK4SoI/AAAAAAAAzhU/artF9l_i5-8PUhSIchshYDV2SOuzq1kcgCLcB/s1600/veneno-clash-royale-rara-epica.png" },
  { "nome": "Fúria", "emojis": ["🫙", "💢", "⚡"], "foto": "https://1.bp.blogspot.com/-A25anUwhAO4/WQExSMEOh_I/AAAAAAAAzfE/siqc3RdU4MQzrj8piFNQrrBG3yjuIo7AACLcB/s1600/furia-clash-royale-card-epica.png" },
  { "nome": "Espelho", "emojis": ["🪞", "🔁", "✨"], "foto": "https://1.bp.blogspot.com/-anwba8rq_44/WQExQ_5GpdI/AAAAAAAAzeU/DqqKCReF_fkahfgb08QMArhco_O-6dp5ACLcB/s1600/espelho-clash-royale-mirror-card.png" },
  { "nome": "Clone", "emojis": ["🧪", "👯", "🔁"], "foto": "https://2.bp.blogspot.com/-I2ONajoj70I/WQExQb5VdYI/AAAAAAAAzeI/vLX3DxL51wsJl8638nRcHhNWqwcKi9B5QCLcB/s1600/clone-clash-royale.png" },
  { "nome": "Tornado", "emojis": ["🌪️", "💨", "🔄"], "foto": "https://2.bp.blogspot.com/-t7QzrCywv1o/WQExVjEVJRI/AAAAAAAAzg8/vT1qH4PERhErdwhMIhDYXZfif_orasnFQCLcB/s1600/tornado-clash-royale.png" },
  { "nome": "Gelo", "emojis": ["❄️", "🧊", "🫙"], "foto": "https://4.bp.blogspot.com/-CO9J5mVvDTo/WQExRvcFrhI/AAAAAAAAze0/vJN16iN0doABNK-VqRYV1YRK72o5aoUXgCLcB/s1600/feitico-de-gelo-clash-royale-card.png" },
  { "nome": "Cemitério", "emojis": ["⚰️", "💀", "🌑"], "foto": "https://4.bp.blogspot.com/-h79UyyyEN4o/WQExQE9_VTI/AAAAAAAAzeA/Q5EJZFKB7TEzQk2FK0seGLoAOuQNhLHSQCLcB/s1600/cemiterio-clash-royale.png" },
  { "nome": "Barril de Goblins", "emojis": ["🛢️", "👺", "💥"], "foto": "https://3.bp.blogspot.com/-rcgZZDTgva0/WQExPFD81SI/AAAAAAAAzdg/c3aXuUuZR7oiqPPt9gFjNoeVoyhzoXsOQCLcB/s1600/barril-de-goblins-clash-royale-carta-epica.png" },
  { "nome": "Lenhador", "emojis": ["🪓", "👨‍🦰", "🍺"], "foto": "https://3.bp.blogspot.com/-dUBEu-CKl0o/WQExTsC2djI/AAAAAAAAzf8/aZw49oQ6vdoDm3T32DX1P_or_OaKl3G_gCLcB/s1600/lenhador-clash-royale-carta-lendaria.png" },
  { "nome": "Mago Elétrico", "emojis": ["🧙‍♂️", "⚡", "🔌"], "foto": "https://4.bp.blogspot.com/-LBMgRUMbEAQ/WQExUAXpTAI/AAAAAAAAzgI/j81YAkvTcRgK5M-BhC4vdSksmvzfLn8KQCLcB/s1600/mago-eletrico-clash-royale-eletric-wizard.png" },
  { "nome": "Bandida", "emojis": ["👩‍🎤", "💨", "😈"], "foto": "https://4.bp.blogspot.com/-UUWmRcoGtds/WQE3suUQEpI/AAAAAAAAzho/dH43zMItrHIkqdjf8DE1HJfdndhTAKOcgCLcB/s1600/bandida-clash-royale-wiki.png" },
  { "nome": "Gangue de Goblins", "emojis": ["👺", "👥", "🗡️"], "foto": "https://1.bp.blogspot.com/-WgKeRSV-VKs/WQExSf1q64I/AAAAAAAAzfI/0PyISQya79MoZX4Jy3ll7PEKundJ2TFTQCLcB/s1600/gangue-de-goblins-clash-royale.png" },
  { "nome": "Tronco", "emojis": ["🌳", "🪵"], "foto": "https://4.bp.blogspot.com/-k-MpaFcNzUM/WQExWLHkveI/AAAAAAAAzhM/saK0yZmVYAUYCUB1WmUfy-14FNgPNn8RgCLcB/s1600/tronco-clash-royale.png" },
  { "nome": "Fantasma Real", "emojis": ["👻", "👑", "🗡️"], "foto": "https://www.clashroyaledicas.com/wp-content/uploads/2017/12/fantasma-real-carta-lendaria-wiki-clash-royale.png" },
  { "nome": "Caçador", "emojis": ["🧔🏻‍♂️", "🔫", "🦆"], "foto": "https://www.clashroyaledicas.com/wp-content/uploads/2017/12/cacador-clash-royale.png" },
  { "nome": "Mega Cavaleiro", "emojis": ["💪", "🥊", "🛡️"], "foto": "https://3.bp.blogspot.com/-FZDIiY9YgIQ/WT6q0dvOX-I/AAAAAAAA1UI/h0PoTthQdOkyef9SqiOjFWNTQqsab8z6ACLcB/s1600/megacavaleiro-clash-royale.png" },
  { "nome": "Aríete de Batalha", "emojis": ["🪵", "🏃", "💥"], "foto": "https://1.bp.blogspot.com/-SxIYMcD6tbA/WQExOdbblsI/AAAAAAAAzdM/GdBKhKlxrecqRmfOcSZ2Ly2pia-Q0HXnQCLcB/s1600/ariete-de-batalha-clash-royale-batle-ram.png" },
  { "nome": "Carrinho de Canhão", "emojis": ["🛺", "🔫", "🛡️"], "foto": "https://4.bp.blogspot.com/-9ytR5U12vSo/WT6UqeH_dbI/AAAAAAAA1S8/3Y3VNUaxUOwIVPSl2N-Zks48Tr0RZUYVACLcB/s1600/carrinho-de-canhao-clash-royale.png" },
  { "nome": "Máquina Voadora", "emojis": ["🛩️", "🔫", "⚙️"], "foto": "https://www.clashroyaledicas.com/2016/01/todas-cartas-de-clash-royale-wiki.html" },
  { "nome": "Dragão Elétrico", "emojis": ["🐲", "⚡", "🔌"], "foto": "https://www.clashroyaledicas.com/wp-content/uploads/2018/10/carta-dragao-eletrico-no-clash-royale.png" },
  { "nome": "Recrutas Reais", "emojis": ["⚔️", "🛡️", "👑"], "foto": "https://www.clashroyaledicas.com/wp-content/uploads/2018/07/carta-recrutas-reais.png" },
  { "nome": "Goblin com Dardo", "emojis": ["👺", "🏹", "🎯"], "foto": "https://4.bp.blogspot.com/-OVRMdQdLcf8/WQExSsSyeRI/AAAAAAAAzfU/Ivz2jFOeKB4ohQ8w46gy7MZ8kYyHm1MsQCLcB/s1600/goblin-com-dardos-clash-royale.png" },
  { "nome": "Lava Hound", "emojis": ["🐶", "🔥", "💨"], "foto": "https://3.bp.blogspot.com/-ufMvZS82riE/WQExTm0gajI/AAAAAAAAzf4/MsJnlat0Xzkk48wqSml7hvfvZ3veceVGgCLcB/s1600/lava-hound-clash-royale.png" },
  { "nome": "Guardas", "emojis": ["🛡️", "💀", "⚔️"], "foto": "https://1.bp.blogspot.com/-XVcNOW3KEmM/WQExTCbwFNI/AAAAAAAAzfo/1zJ7aJIy0XQlCj7jHBPPMLzlnxNfJtkZQCLcB/s1600/guardas-clash-royale.png" },
  { "nome": "Arqueiro Mágico", "emojis": ["🏹", "🧙‍♂️", "✨"], "foto": "https://www.clashroyaledicas.com/wp-content/uploads/2018/02/arqueiro-magico-clash-royale.png" },
  { "nome": "Gigante Real", "emojis": ["👑", "👹", "🔫"], "foto": "https://www.clashroyaledicas.com/wp-content/uploads/2016/03/gigante-real-wiki-da-carta.png" },
  { "nome": "Lápide", "emojis": ["🪦", "💀", "⚰️"], "foto": "https://3.bp.blogspot.com/-9MMPqnrY3mA/WQExTdsDHOI/AAAAAAAAzf0/EokDMXRYFasWNhjxy5xueMpIwUnCR_howCLcB/s1600/lapide-tombstone-clash-royale.png" },
  { "nome": "Fênix", "emojis": ["🐦", "🔥", "♻️"], "foto": "https://www.clashroyaledicas.com/wp-content/uploads/2022/10/carta-lendaria-fenix-clash-royale-phoenix-269x300.png" },
  { "nome": "Jaula de goblin", "emojis": ["👺", "🔒", "🔑"], "foto": "https://www.clashroyaledicas.com/wp-content/uploads/2019/07/carta-jaula-de-goblin-clash-royale-250x300.png" },
  { "nome": "Terremoto", "emojis": ["🧪", "💥", "🎌"], "foto": "https://www.clashroyaledicas.com/wp-content/uploads/2019/04/carta-terremoto-clash-royale.png" },
  { "nome": "Cavaleiro Dourado", "emojis": ["🤴", "💛", "⚔️"], "foto": "https://www.clashroyaledicas.com/wp-content/uploads/2021/10/carta-campeao-cavaleiro-dourado-clash-royale-golden-knight-214x300.png" },
  { "nome": "Rainha Arqueira", "emojis": ["👸", "🏹", "🎯"], "foto": "https://www.clashroyaledicas.com/wp-content/uploads/2021/10/carta-campea-rainha-arqueira-clash-royale-archer-queen-214x300.png" },
  { "nome": "Escavadeira de Goblins", "emojis": ["👺", "🚜", "💨"], "foto": "https://www.clashroyaledicas.com/wp-content/uploads/2021/06/goblin-com-broca-wiki-da-carta.png" },
  { "nome": "Dragões Esqueleto", "emojis": ["🐉", "☠️", "2️⃣"], "foto": "https://www.clashroyaledicas.com/wp-content/uploads/2020/05/carta-dragoes-esqueleto-clash-royale.png" },
  { "nome": "Golem de elixir", "emojis": ["🩸", "🩷", "😈"], "foto": "https://www.clashroyaledicas.com/wp-content/uploads/2019/10/carta-golem-de-elixir-clash-royale-250x300.png" },
  { "nome": "Eletrocutadores", "emojis": ["🛒", "⚡", "3️⃣"], "foto": "https://www.clashroyaledicas.com/wp-content/uploads/2017/12/eletrocutadores-clash-royale.png" },
  { "nome": "Spark", "emojis": ["🛒", "⚡", "💥"], "foto": "https://3.bp.blogspot.com/-L7uHNRgWiqc/WQExVcPHsTI/AAAAAAAAzg0/1yPwtlUzzS4n4r7O71jbVJ8ub9ozlp4jACLcB/s1600/sparky-clash-royale.png" },
  { "nome": "Mineiro", "emojis": ["⛏️", "👷‍♂️", "💣"], "foto": "https://1.bp.blogspot.com/-F_e-xLUgi_0/WQExUf6qcqI/AAAAAAAAzgU/yAg6zLq89csfy14QAG-oZhZy1zCDvrmbgCLcB/s1600/mineiro-clash-royale.png" },
  { "nome": "Pescador", "emojis": ["🎣", "👨‍🦰", "💦"], "foto": "https://www.clashroyaledicas.com/wp-content/uploads/2020/02/carta-pescador-clash-royale.png" },
  { "nome": "Bruxa Mãe", "emojis": ["🧙‍♀️", "🐷", "✨"], "foto": "https://www.clashroyaledicas.com/wp-content/uploads/2020/12/bruxa-mae-wiki-da-carta.png" },
  { "nome": "Encomenda Real", "emojis": ["📦", "👑", "🛡️"], "foto": "https://www.clashroyaledicas.com/wp-content/uploads/2020/03/carta-encomenda-real-clash-royale.png" },
  { "nome": "Gigante Esqueleto", "emojis": ["💀","💣","💥"], "foto": "https://4.bp.blogspot.com/-LZCqCa7dDP0/WQExRepiNmI/AAAAAAAAzek/7HojWV1-ldwQBiZ70pryWPPq5Jv1NFzqQCLcB/s1600/esqueleto-gigante-clash-royale-card-epic.png" },
  { "nome": "Goblin Gigante", "emojis": ["👺", "👹", "⚡"], "foto": "https://www.clashroyaledicas.com/wp-content/uploads/2018/09/carta-goblin-gigante-no-clash-royale.png" },
  { "nome": "Golem de Gelo", "emojis": ["🪨", "❄️", "💥"], "foto": "https://4.bp.blogspot.com/-dle5TWsTlhY/WQExS6k8UeI/AAAAAAAAzfk/Q5miu9DQxgQipFlha5q8x-TK4alFHGzRACLcB/s1600/golem-de-gelo-clash-royale.png" },
  { "nome": "Espírito de Gelo", "emojis": ["❄️", "👻", "💨"], "foto": "https://4.bp.blogspot.com/-IYWkKg3IDVY/WQExRKhHKGI/AAAAAAAAzec/wP-7g4M9qlEH2lquKBskZ2DEKG8sqINQgCLcB/s1600/espirito-de-gelo-clash-royale.png" },
  { "nome": "Espírito de Fogo", "emojis": ["🔥", "👻", "💨"], "foto": "https://www.clashroyaledicas.com/wp-content/uploads/2016/05/carta-espirito-de-fogo-clash-royale.png" },
  { "nome": "Espírito Elétrico", "emojis": ["⚡", "👻", "💨"], "foto": "https://www.clashroyaledicas.com/wp-content/uploads/2020/10/carta-espirito-eletrico-clash-royale.png" },
  { "nome": "Gigante Elétrico", "emojis": ["⚡", "👓", "👨🏻‍🦰"], "foto": "https://www.clashroyaledicas.com/wp-content/uploads/2022/04/carta-gigante-eletrico-clash-royale.png" },
  { "nome": "Espírito Curador", "emojis": ["💛", "👻", "✨"], "foto": "https://www.clashroyaledicas.com/wp-content/uploads/2020/04/carta-espirito-curador-clash-royale.png" },
  { "nome": "Pirotecnica", "emojis": ["🧨", "🎆", "🔫"], "foto": "https://www.clashroyaledicas.com/wp-content/uploads/2020/01/carta-pirotecnica-clash-royale.png" },
  { "nome": "Curadora Guerreira", "emojis": ["👩🏼", "🪽", "💛"], "foto": "https://www.clashroyaledicas.com/wp-content/uploads/2019/11/carta-curadora-guerreira-clash-royale.png" },
  { "nome": "Porcos Reais", "emojis": ["🐷", "👑", "💨"], "foto": "https://www.clashroyaledicas.com/wp-content/uploads/2018/06/carta-porcos-reais-no-clash-royale.png" },
  { "nome": "Coletor de Elixir", "emojis": ["🩸", "🛢️", "💰"], "foto": "https://3.bp.blogspot.com/-wD3i8gB7xY0/WQExQLfT3XI/AAAAAAAAzd4/3-vWZz6qotc2Jh7iAmWaX2Eo70eb2kzJQCLcB/s1600/card-coletor-de-elixir-clash-royale.png" },
  { "nome": "Morteiro", "emojis": ["🧨", "🏰", "💥"], "foto": "https://www.clashroyaledicas.com/wp-content/uploads/2019/07/carta-morteiro-clash-royale.png" },
  { "nome": "Aríete de Batalha", "emojis": ["🪵", "🏃", "💥"], "foto": "https://1.bp.blogspot.com/-SxIYMcD6tbA/WQExOdbblsI/AAAAAAAAzdM/GdBKhKlxrecqRmfOcSZ2Ly2pia-Q0HXnQCLcB/s1600/ariete-de-batalha-clash-royale-batle-ram.png" },
  { "nome": "Monge", "emojis": ["🧘", "⚔️", "🔥"], "foto": "https://www.clashroyaledicas.com/wp-content/uploads/2022/10/carta-campeao-monge-clash-royale-monk-214x300.png" },
  { "nome": "Mineiro Bombado", "emojis": ["💪🏻", "⛏️", "⛑️"], "foto": "https://www.clashroyaledicas.com/wp-content/uploads/2022/03/carta-campeao-mineiro-bombado-clash-royale-mighty-miner-214x300.png" },
  { "nome": "Rei Esqueleto", "emojis": ["☠️", "👑", "⚔️"], "foto": "https://www.clashroyaledicas.com/wp-content/uploads/2021/10/carta-campeao-rei-esqueleto-clash-royale-skeleton-king-214x300.png" },
  { "nome": "Patifes", "emojis": ["👨‍👧‍👧", "⚔️", "🤕"], "foto": "https://www.clashroyaledicas.com/wp-content/uploads/2018/05/patifes-clash-royale.png" },
  { "nome": "Morcegos", "emojis": ["🦇", "🦇", "🦇"], "foto": "https://3.bp.blogspot.com/-nHkyLF1BlVM/WQE4KgUxIRI/AAAAAAAAzhs/Sm7K8NqBSoI9F3X18OPKn35e88ai_1OwQCLcB/s1600/morcego-clash-royale-wiki.png" },
  { "nome": "Foguete", "emojis": ["🚀", "💥", "🔥"], "foto": "https://3.bp.blogspot.com/-y8UeOivyPzE/WQExR94rwzI/AAAAAAAAze8/oTY2X8Wg8Z803XMLJZrhy6E9qXE5QayfwCLcB/s1600/foguete-clash-royale-card-rocket-foquete.png" },
  { "nome": "Zap", "emojis": ["⚡", "💥", "🔋"], "foto": "https://2.bp.blogspot.com/-NMkKSq7Aq98/WQExQQXrn0I/AAAAAAAAzeE/aO-UA-L_opsfPAN0iBuljo1MsU4XMXCHQCLcB/s1600/choque-clash-royale-zap.png" },
  { "nome": "Barril de Bárbaro", "emojis": ["🛢️", "⚔️", " 🏃"], "foto": "https://www.clashroyaledicas.com/wp-content/uploads/2018/03/barril-de-barbaro-do-clash-royale.png" },
  { "nome": "Barril de Esqueleto", "emojis": ["🎈", "🛢️", "💀"], "foto": "http://1.bp.blogspot.com/-IOe11fzh6ZM/WT6ZOooHVII/AAAAAAAA1TE/SduFiLUjr8UaHd17kso2uQOgcOr__589ACLcB/s1600/barril-de-goblins-clash-royale.png" },
  { "nome": "Balão", "emojis": ["🎈", "💣", "💥"], "foto": "https://2.bp.blogspot.com/-0s1m89V9OM4/WQExO2Q3IfI/AAAAAAAAzdQ/fAyLhKInLRQj1Yk4vVyC1GyKqPzJSOoZQCLcB/s1600/balao-clash-royale-balloon.png" },
  { "nome": "Goblins Lanceiros", "emojis": ["👺", "🏹", "🗡️"], "foto": "https://4.bp.blogspot.com/-SW8Ukdyhu6Y/WQExS2ot9BI/AAAAAAAAzfc/wenfJsNgVp0D8p5JQsarn-kxvFtUbsDqQCLcB/s1600/goblins-com-lancas-clash-royale.png" },
  { "nome": "Bárbaros", "emojis": ["⚔️", "👨", "💪"], "foto": "https://1.bp.blogspot.com/-onHMBGPfMMA/WQExO0LfN_I/AAAAAAAAzdU/hazXmX8uhMMSnJJ-dpZpzIl3B6uJ5Vd9ACLcB/s1600/barbaro-clash-royale.png" },
  { "nome": "Bárbaros de elite", "emojis": ["🧑🏻‍🤝‍🧑🏻", "⚔️", "💪"], "foto": "https://2.bp.blogspot.com/-5L6cA0o7eGE/WQExOxXwhVI/AAAAAAAAzdY/wpAmG7ZRaxoEKItCjhtiEKPEAayTWthwgCLcB/s1600/barbaros-de-elite-clash-royale.png" },
  { "nome": "Servos", "emojis": ["👾", "👾", "👾"], "foto": "https://3.bp.blogspot.com/-3O1sHkiS6L0/WQExVRAv7fI/AAAAAAAAzgw/DM3IMFbu5O8SOokNAu6bcXf9-UW63FfyACLcB/s1600/servos-clash-royale-dicas.png" },
  { "nome": "Relampago", "emojis": ["⚡", "🫙", "🌩️"], "foto": "https://4.bp.blogspot.com/-9BY9q3Qs_7Y/WQExVMrlbJI/AAAAAAAAzgs/WJG_40Wc0AMQ_xPaSNmOdHBamOmjZMrmQCLcB/s1600/relampago-clash-royale-carta-epica.png" }
]

export default ClashCards;
